package com.example.task1new

const val COUNTRY_NAME_BUNDLE_KEY = "COUNTRY_NAME_BUNDLE_KEY"
const val COUNTRY_FLAG_URL_BUNDLE_KEY = "COUNTRY_NAME_BUNDLE_KEY"
const val COUNTRY_DETAILS_LAYOUT_MANAGER_KEY = "COUNTRY LAYOUT MANAGER KEY"


const val COUNTRY_LIST_ADAPTER_DATA_LIST_KEY = "COUNTRY LAYOUT MANAGER KEY"