package com.example.task1new

//Country Details Fragment
const val COUNTRY_DETAILS_BUNDLE_ERROR = "BUNDLE ERROR"

const val COUNTRY_NAME_BUNDLE_KEY = "COUNTRY_NAME_BUNDLE_KEY"
const val COUNTRY_DETAILS_LAYOUT_MANAGER_KEY = "COUNTRY LAYOUT MANAGER KEY"


//Const for filter

const val FILTER_MINIMUM_AREA_BUNDLE_KEY = "ADAPTER_MINIMUM_AREA_BUNDLE_KEY"
const val FILTER_MAXIMUM_AREA_BUNDLE_KEY = "ADAPTER_MAXIMUM_AREA_BUNDLE_KEY"
const val FILTER_MINIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MINIMUM_POPULATION_BUNDLE_KEY"
const val FILTER_MAXIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MAXIMUM_POPULATION_BUNDLE_KEY"
const val FILTER_MAXIMUM_DISTANCE_BUNDLE_KEY = "ADAPTER_MAXIMUM_DISTANCE_BUNDLE_KEY"

const val DTO_DEFAULT_DISTANCE_VALUE = "Failed to compute distance"
const val FILTER_ANY_COUNTRY_VALUE = "AnyCountry"