package com.example.task1new

const val COUNTRY_NAME_BUNDLE_KEY = "COUNTRY_NAME_BUNDLE_KEY"
const val COUNTRY_DETAILS_LAYOUT_MANAGER_KEY = "COUNTRY LAYOUT MANAGER KEY"

const val MIN_SEARCH_STRING_LENGTH = 3
const val DEBOUNCE_TIME_MILLIS = 500L
