package com.example.task1new

const val COUNTRY_NAME_BUNDLE_KEY = "COUNTRY_NAME_BUNDLE_KEY"
const val COUNTRY_DETAILS_LAYOUT_MANAGER_KEY = "COUNTRY LAYOUT MANAGER KEY"


//Const for filter

const val ADAPTER_MINIMUM_AREA_BUNDLE_KEY = "ADAPTER_MINIMUM_AREA_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_AREA_BUNDLE_KEY = "ADAPTER_MAXIMUM_AREA_BUNDLE_KEY"

const val ADAPTER_MINIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MINIMUM_POPULATION_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MAXIMUM_POPULATION_BUNDLE_KEY"

const val ADAPTER_MINIMUM_DISTANCE_BUNDLE_KEY = "ADAPTER_MINIMUM_DISTANCE_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_DISTANCE_BUNDLE_KEY = "ADAPTER_MAXIMUM_DISTANCE_BUNDLE_KEY"