package com.example.task1new

//Const for filter

const val ADAPTER_MINIMUM_AREA_BUNDLE_KEY = "ADAPTER_MINIMUM_AREA_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_AREA_BUNDLE_KEY = "ADAPTER_MAXIMUM_AREA_BUNDLE_KEY"
const val ADAPTER_MINIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MINIMUM_POPULATION_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_POPULATION_BUNDLE_KEY = "ADAPTER_MAXIMUM_POPULATION_BUNDLE_KEY"
const val ADAPTER_MAXIMUM_DISTANCE_BUNDLE_KEY = "ADAPTER_MAXIMUM_DISTANCE_BUNDLE_KEY"
const val DTO_DEFAULT_DISTANCE_VALUE = "Failed to compute distance"
const val FILTER_ANY_COUNTRY_VALUE = "AnyCountry"
